version: "3.8"

services:
  mongo:
    image: mongo:7.0
    container_name: campus_mongo
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: campus_redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis_data:/data

  api:
    build: .
    container_name: campus_api
    ports:
      - "5050:5050"
    restart: always
    depends_on:
      - mongo
      - redis
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://mongo:27017/campus-backend
      - REDIS_URL=redis://redis:6379
      - PORT=5050

volumes:
  mongo_data:
  redis_data:
